airbnb_app/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views


app_name = 'accounts'

urlpatterns = [
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
    ),
    path(
        route='logout/',
        view=auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path('activate/<uidb64>/<token>/', views.AccountActivationView.as_view(), name='activate'),
    path('activation-required/', views.ActivationRequiredView.as_view(), name='activation_required'),

    path('settings/', views.AccountSettingsDashboardView.as_view(), name='settings_dashboard'),
    path('settings/personal-info/', views.PersonalInfoEditView.as_view(), name='user_info_edit'),

    path('settings/login-and-security/', views.SecurityDashboardView.as_view(), name='security_dashboard'),
    path(
        route='settings/login-and-security/confirm-phone/',
        view=views.PhoneNumberConfirmPageView.as_view(),
        name='confirm_phone',
    ),
    path('settings/login-and-security/confirm-email/', views.SendConfirmationEmailView.as_view(), name='confirm_email'),

    path('show/<int:user_pk>/', views.ProfileShowView.as_view(), name='profile_show'),
    path('edit-image/', views.ProfileImageEditView.as_view(), name='edit_image'),
    path('edit-description/', views.ProfileDescriptionEditView.as_view(), name='edit_description'),

    # password change urls
    path(
        route='password_change/',
        view=auth_views.PasswordChangeView.as_view(
            template_name='accounts/registration/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done'),
         ),
        name='password_change',
    ),
    path(
        route='password_change/done/',
        view=auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
        name='password_change_done',
    ),

    # password reset urls
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path(
        route='password_reset/done/',
        view=auth_views.PasswordResetDoneView.as_view(template_name='accounts/registration/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        route='reset/<uidb64>/<token>/',
        view=auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
         ),
        name='password_reset_confirm',
    ),
    path(
        route='reset/done/',
        view=auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/registration/password_reset_complete.html',
         ),
        name='password_reset_complete',
    ),
]

airbnb_app/main/urls.py
from django.http import HttpResponse
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page'),
    path('healthcheck/', lambda response: HttpResponse(), name='healthcheck'),
    path('robots.txt', views.RobotsView.as_view(), name='robots'),
]

airbnb_app/accounts/api/views.py
from rest_framework_simplejwt.views import TokenObtainPairView

from .serializers import CustomTokenObtainPairSerializer


class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer

airbnb_app/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpRequest
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.views import generic

from common.constants import (
    TWILIO_MESSAGE_STATUS_CODES_FAILED, VERIFICATION_CODE_STATUS_DELIVERED, VERIFICATION_CODE_STATUS_FAILED,
)
from common.types import AuthenticatedHttpRequest
from hosts.services import get_host_or_none_by_user
from realty.services.realty import get_available_realty_by_host

from .constants import (
    EMAIL_CONFIRMATION_FAILURE_RESPONSE_MESSAGE, EMAIL_CONFIRMATION_SUCCESS_RESPONSE_MESSAGE,
    EMAIL_SENT_SUCCESSFULLY_RESPONSE_MESSAGE, PHONE_NUMBER_CONFIRMATION_SUCCESS_RESPONSE_MESSAGE,
    PROFILE_INFO_EDIT_SUCCESS_RESPONSE_MESSAGE, SMS_CODE_INVALID_RESPONSE_MESSAGE, SMS_NOT_DELIVERED_RESPONSE_MESSAGE,
    SMS_SENT_SUCCESSFULLY_RESPONSE_MESSAGE,
)
from .forms import (
    CustomPasswordResetForm, ProfileDescriptionForm, ProfileForm, ProfileImageForm, SignUpForm, UserInfoForm,
    VerificationCodeForm,
)
from .mixins import AnonymousUserRequiredMixin, UnconfirmedEmailRequiredMixin, UnconfirmedPhoneNumberRequiredMixin
from .models import CustomUser, Profile
from .services import (
    create_jwt_token_for_user_with_additional_fields, get_phone_code_status_by_user_id, get_user_by_pk,
    get_user_from_uid, get_verification_code_from_digits_dict, handle_phone_number_change,
    is_verification_code_for_profile_valid, send_verification_link, set_phone_code_status_by_user_id,
    update_phone_number_confirmation_status, update_user_email_confirmation_status,
)
from .tokens import account_activation_token


class SignUpView(
    AnonymousUserRequiredMixin,
    generic.base.TemplateResponseMixin,
    generic.View,
):
    """View for creating a new account."""

    form_class = SignUpForm
    template_name = 'accounts/registration/signup.html'

    def get(self, request: HttpRequest, *args, **kwargs):
        return self.render_to_response(
            context={
                'form': self.form_class(),
            },
        )

    def post(self, request: HttpRequest, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save()
            create_jwt_token_for_user_with_additional_fields(user=user)
            send_verification_link(get_current_site(request).domain, request.scheme, user)
            return redirect('accounts:login')

        return self.render_to_response(
            context={
                'form': form,
            },
        )


class LoginView(
    AnonymousUserRequiredMixin,
    auth_views.LoginView,
):
    """View for signing in."""

    template_name = 'accounts/registration/login.html'


class CustomPasswordResetView(auth_views.PasswordResetView):
    """View for resetting a password."""

    template_name = 'accounts/registration/password_reset.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    html_email_template_name = 'accounts/registration/password_reset_email.html'
    email_template_name = 'accounts/registration/password_reset_email.html'
    form_class = CustomPasswordResetForm


class AccountActivationView(generic.View):
    """View for confirming user's email."""

    def get(self, request: HttpRequest, uidb64, token, *args, **kwargs):
        try:
            user = get_user_from_uid(uidb64)
        except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user = update_user_email_confirmation_status(user=user, is_email_confirmed=True)
            create_jwt_token_for_user_with_additional_fields(user=user)
            login(request, user)
            messages.add_message(request, messages.SUCCESS, EMAIL_CONFIRMATION_SUCCESS_RESPONSE_MESSAGE)
            return redirect(reverse('home_page'))

        messages.add_message(request, messages.ERROR, EMAIL_CONFIRMATION_FAILURE_RESPONSE_MESSAGE)
        return redirect(reverse('home_page'))


class ActivationRequiredView(generic.TemplateView):
    """Display error page - page requires confirmed email."""

    template_name = 'accounts/registration/account_activation_required.html'


class AccountSettingsDashboardView(
    LoginRequiredMixin,
    generic.TemplateView,
):
    """View for showing an account dashboard."""

    template_name = 'accounts/settings/settings_dashboard.html'


class PersonalInfoEditView(
    LoginRequiredMixin,
    generic.base.TemplateResponseMixin,
    generic.View,
):
    """View for editing user personal info."""

    template_name = 'accounts/settings/user_form.html'
    profile_form: ProfileForm = None
    user_info_form: UserInfoForm = None

    def dispatch(self, request: AuthenticatedHttpRequest, *args, **kwargs):
        self.profile_form = ProfileForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=request.user.profile,
        )
        self.user_info_form = UserInfoForm(
            data=request.POST or None,
            instance=request.user,
        )
        return super(PersonalInfoEditView, self).dispatch(request, *args, **kwargs)

    def get(self, request: HttpRequest, *args, **kwargs):
        return self.render_to_response(
            context={
                'user_info_form': self.user_info_form,
                'profile_form': self.profile_form,
            },
        )

    def post(self, request: HttpRequest, *args, **kwargs):
        if self.user_info_form.is_valid() and self.profile_form.is_valid():
            user: CustomUser = self.user_info_form.save()
            user_profile: Profile = self.profile_form.save()
            profile_cleaned_data = self.profile_form.cleaned_data
            user_id = self.request.user.id

            # if email has been changed
            if 'email' in self.user_info_form.changed_data:
                messages.add_message(request, messages.SUCCESS, EMAIL_SENT_SUCCESSFULLY_RESPONSE_MESSAGE)
                update_user_email_confirmation_status(user, is_email_confirmed=False)
                send_verification_link(get_current_site(request).domain, request.scheme, user)

            # if phone number has been changed or verification code hasn't been delivered
            if (
                    'phone_number' in self.profile_form.changed_data or
                    get_phone_code_status_by_user_id(user_id) == VERIFICATION_CODE_STATUS_FAILED
            ):
                if profile_cleaned_data.get('phone_number', None):  # if it is not blank
                    twilio_payload = handle_phone_number_change(
                        user_profile=user_profile,
                        site_domain=get_current_site(request).domain,
                        new_phone_number=str(profile_cleaned_data.get('phone_number')),
                    )

                    # if SMS code hasn't been sent yet
                    failed_status_codes = (TWILIO_MESSAGE_STATUS_CODES_FAILED, VERIFICATION_CODE_STATUS_FAILED)
                    if twilio_payload.status.lower() in failed_status_codes:
                        set_phone_code_status_by_user_id(
                            user_id=user_id,
                            phone_code_status=VERIFICATION_CODE_STATUS_FAILED,
                        )
                        messages.add_message(request, messages.ERROR, SMS_NOT_DELIVERED_RESPONSE_MESSAGE)
                    else:
                        set_phone_code_status_by_user_id(
                            user_id=user_id,
                            phone_code_status=VERIFICATION_CODE_STATUS_DELIVERED,
                        )
                        messages.add_message(request, messages.SUCCESS, SMS_SENT_SUCCESSFULLY_RESPONSE_MESSAGE)
                else:  # if phone number has been removed
                    update_phone_number_confirmation_status(user_profile, is_phone_number_confirmed=False)

            if self.profile_form.changed_data or self.user_info_form.changed_data:
                messages.add_message(request, messages.SUCCESS, PROFILE_INFO_EDIT_SUCCESS_RESPONSE_MESSAGE)
            return redirect('accounts:user_info_edit')

        return self.render_to_response(
            context={
                'user_info_form': self.user_info_form,
                'profile_form': self.profile_form,
            },
        )


class ProfileShowView(
    generic.base.TemplateResponseMixin,
    generic.View,
):
    """View for displaying a user profile."""

    template_name = 'accounts/profile/show.html'

    profile_owner: CustomUser = None
    is_profile_of_current_user: bool = False  # True if the profile is the current user's profile, False otherwise

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        self.profile_owner = get_user_by_pk(pk=kwargs.get('user_pk'))

        if self.profile_owner == request.user:
            self.is_profile_of_current_user = True

        return super(ProfileShowView, self).dispatch(request, *args, **kwargs)

    def get(self, request: HttpRequest, *args, **kwargs):
        host_listings = get_available_realty_by_host(
            realty_host=get_host_or_none_by_user(user=self.profile_owner),
        )

        return self.render_to_response(
            context={
                'profile_owner': self.profile_owner,
                'is_profile_of_current_user': self.is_profile_of_current_user,
                'host_listings': host_listings,
            },
        )


class ProfileImageEditView(
    LoginRequiredMixin,
    generic.base.TemplateResponseMixin,
    generic.View,
):
    """View for editing a profile image."""

    template_name = 'accounts/profile/edit_image.html'

airbnb_app/accounts/templates/accounts/settings/confirm_phone.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Confirm phone number &bull; Login & Security &bull; Air
{% endblock %}

{% block content %}
    <div class="account--confirm-phone">
        <div class="confirm-phone--header">
            <div class="account--links">
                <span class="account--link">
                    <a href="{% url 'accounts:security_dashboard' %}">Login & Security</a>
                </span>
                <span class="account--link active">
                    Confirm phone number
                </span>
            </div>
            <h1>Confirm phone number</h1>
        </div>

        <div class="confirm-phone">
            <hr>

            {% if is_verification_code_sent %}
                <p>
                    We've sent you the 4 digit code to {{ phone_number }}
                    <br>
                    Enter the code below to confirm your phone number.
                </p>
            {% else %}
                <p>There was an error while sending a verification code. Try again later or contact our support</p>
            {% endif %}

            <div class="code-container">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ verification_code_form }}

                    <div class="form-buttons">
                        <input type="submit" class="button-secondary" value="Confirm">
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block domready %}
    const codes = document.querySelectorAll('.code');

    codes[0].focus();

    codes.forEach((code, idx) => {
        code.addEventListener('keydown', (e) => {
            if(e.key >= 0 && e.key <=9) {
                codes[idx].value = '';
                setTimeout(() => codes[idx + 1].focus(), 10);
            } else if(e.key === 'Backspace') {
                setTimeout(() => codes[idx - 1].focus(), 10);
            }
        })
    })
{% endblock %}

airbnb_app/accounts/templates/accounts/settings/security_dashboard.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Login & Security &bull; Account Settings &bull; Air
{% endblock %}

{% block content %}
    <div class="account--security">
        <div class="security--header">
            <div class="account--links">
                <span class="account--link">
                    <a href="{% url 'accounts:settings_dashboard' %}">Account</a>
                </span>
                <span class="account--link active">
                    Login & Security
                </span>
            </div>
            <h1>Login & Security</h1>
        </div>

        <div class="security--settings">
            <hr>
            <div class="login-section security-section">
                <h2>Login</h2>

                <div class="update-password">
                    <div class="section-info">
                        <p>Password</p>
                    </div>
                    <a href="{% url 'accounts:password_change' %}" class="account-dashboard--link">Update</a>
                </div>
            </div>
            <hr>
            <div class="verification-section security-section">
                <h2>Confirm your details</h2>

                <div class="confirm-phone">
                    <div class="section-info">
                        <p>Phone number</p>
                        {% if phone_number %}
                            <p class="color-secondary">{{ phone_number }}</p>
                        {% else %}
                            <p class="color-secondary">No phone number yet</p>
                        {% endif %}
                    </div>

                    {% if phone_number %}
                        {% if not request.user.profile.is_phone_number_confirmed %}
                                <a href="{% url 'accounts:confirm_phone' %}" class="account-dashboard--link">Confirm</a>
                            {% else %}
                                <p class="account-dashboard--link">
                                    <span class="check-icon"><i class="fas fa-check"></i></span>
                                    <span>Confirmed</span>
                                </p>
                        {% endif %}
                    {% endif %}
                </div>
                <hr>
                <div class="confirm-email">
                    <div class="section-info">
                        <p>Email</p>
                        <p class="color-secondary">{{ email }}</p>
                    </div>

                    {% if not request.user.is_email_confirmed %}
                            <a href="{% url 'accounts:confirm_email' %}" class="account-dashboard--link">Confirm</a>
                        {% else %}
                            <p class="account-dashboard--link">
                                <span class="check-icon"><i class="fas fa-check"></i></span>
                                <span>Confirmed</span>
                            </p>
                    {% endif %}
                </div>
                <hr>

            </div>
        </div>
    </div>

{% endblock %}

airbnb_app/accounts/templates/accounts/settings/settings_dashboard.html
{% extends 'base.html' %}


{% block title %}
    Account Settings &bull; Air
{% endblock %}

{% block content %}
    <div class="account-settings">
        <div class="account--header">
            <h1>Account</h1>
            <div class="general-info">
                <p>
                    <span class="general-info--item">
                        <span class="user--name">{{ request.user.full_name }}</span>, {{ request.user.email }}
                    </span>
                    <span>
                        <a href="{% url 'accounts:profile_show' user_pk=request.user.pk %}">
                            <span class="user--profile-link">Go to profile</span>
                        </a>
                    </span>
                </p>
            </div>
        </div>
        <div class="account--cards">
            <div class="row">
                <div class="col-md-4 col-sm-6">
                    <a href="{% url 'accounts:user_info_edit' %}" class="account-card--link">
                        <div class="account-card card--base">
                            <div class="card--logo">
                                <i class="fas fa-id-card"></i>
                            </div>
                            <div class="card--header">
                                <h2>Personal info <span><i class="fas fa-chevron-right"></i></span></h2>
                            </div>
                            <div class="card--description">
                                <p>Provide personal details and how we can reach you</p>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-md-4 col-sm-6">
                    <a href="{% url 'accounts:security_dashboard' %}" class="account-card--link">
                        <div class="account-card card--base">
                            <div class="card--logo">
                                <i class="fas fa-shield-alt"></i>
                            </div>
                            <div class="card--header">
                                <h2>Login & security <span><i class="fas fa-chevron-right"></i></span></h2>
                            </div>
                            <div class="card--description">
                                <p>Update your password and secure your account</p>
                            </div>
                        </div>
                    </a>
                </div>

                {# TODO: payments & payouts settings #}

                {# TODO: notifications settings #}
            </div>
        </div>
    </div>
{% endblock %}

airbnb_app/accounts/templates/accounts/settings/user_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Personal info
{% endblock %}

{% block content %}
    <div class="account--personal-info">
        <div class="personal-info--header">
            <div class="account--links">
                <span class="account--link">
                    <a href="{% url 'accounts:settings_dashboard' %}">Account</a>
                </span>
                <span class="account--link active">
                    Personal info
                </span>
            </div>
            <h1>Personal info</h1>
        </div>

        <div class="personal-info--settings">
            <div class="personal-info--form">
                <form action="" method="post">
                    {% csrf_token %}
                    {% bootstrap_form user_info_form %}
                    {% bootstrap_form profile_form %}

                    <div class="form-buttons">
                        <input type="submit" class="button button-secondary" value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}