airbnb_app/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views


app_name = 'accounts'

urlpatterns = [
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
    ),
    path(
        route='logout/',
        view=auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path('activate/<uidb64>/<token>/', views.AccountActivationView.as_view(), name='activate'),
    path('activation-required/', views.ActivationRequiredView.as_view(), name='activation_required'),

    path('settings/', views.AccountSettingsDashboardView.as_view(), name='settings_dashboard'),
    path('settings/personal-info/', views.PersonalInfoEditView.as_view(), name='user_info_edit'),

    path('settings/login-and-security/', views.SecurityDashboardView.as_view(), name='security_dashboard'),
    path(
        route='settings/login-and-security/confirm-phone/',
        view=views.PhoneNumberConfirmPageView.as_view(),
        name='confirm_phone',
    ),
    path('settings/login-and-security/confirm-email/', views.SendConfirmationEmailView.as_view(), name='confirm_email'),

    path('show/<int:user_pk>/', views.ProfileShowView.as_view(), name='profile_show'),
    path('edit-image/', views.ProfileImageEditView.as_view(), name='edit_image'),
    path('edit-description/', views.ProfileDescriptionEditView.as_view(), name='edit_description'),

    # password change urls
    path(
        route='password_change/',
        view=auth_views.PasswordChangeView.as_view(
            template_name='accounts/registration/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done'),
         ),
        name='password_change',
    ),
    path(
        route='password_change/done/',
        view=auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
        name='password_change_done',
    ),

    # password reset urls
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path(
        route='password_reset/done/',
        view=auth_views.PasswordResetDoneView.as_view(template_name='accounts/registration/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        route='reset/<uidb64>/<token>/',
        view=auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
         ),
        name='password_reset_confirm',
    ),
    path(
        route='reset/done/',
        view=auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/registration/password_reset_complete.html',
         ),
        name='password_reset_complete',
    ),
]

airbnb_app/hosts/urls.py
from django.urls import path

from . import views


app_name = 'hosts'

urlpatterns = [
    path('become-a-host/', views.BecomeHostView.as_view(), name='become_a_host'),
    path('become-a-host/missing-image/', views.HostMissingImageView.as_view(), name='missing_image'),
]

airbnb_app/main/urls.py
from django.http import HttpResponse
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page'),
    path('healthcheck/', lambda response: HttpResponse(), name='healthcheck'),
    path('robots.txt', views.RobotsView.as_view(), name='robots'),
]

airbnb_app/realty/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from . import views
from .sitemaps import RealtySiteMap


sitemaps = {
    'realty': RealtySiteMap,
}

app_name = 'realty'

urlpatterns = [
    path('', views.RealtyListView.as_view(), name='all'),
    path('search/', views.RealtySearchResultsView.as_view(), name='search'),
    path('rooms/<int:pk>/<slug>/', views.RealtyDetailView.as_view(), name='detail'),
    path('city/<slug:city_slug>/', views.RealtyListView.as_view(), name='all_by_city'),

    # Edit realty
    path('new/', views.RealtyEditView.as_view(), name='new_realty'),
    path('<int:realty_id>/edit/', views.RealtyEditView.as_view(), name='edit_realty'),

    # Realty - steps
    path('new/info/', views.RealtyGeneralInfoEditView.as_view(), name='new_realty_info'),
    path('new/location/', views.RealtyLocationEditView.as_view(), name='new_realty_location'),
    path('new/description/', views.RealtyDescriptionEditView.as_view(), name='new_realty_description'),

    # Images
    path('image/order/', views.RealtyImageOrderView.as_view(), name='image_change_order'),

    # Sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

airbnb_app/subscribers/urls.py
from django.urls import path

from . import views


app_name = 'subscribers'

urlpatterns = [
    path('new-subscription/', views.SubscribeView.as_view(), name='new_subscription'),
]

airbnb_app/templates/components/chat_bot.html
<div id="live-chat">
    <header>
        <h4>
            <span class="chat-bot-header">Air Helper</span>
            <span class="close-chat-bot-btn"><i class="far fa-times-circle"></i></span>
        </h4>
    </header>

    <div class="chat">
        <div class="chat-history"></div>
        <hr>
        <div class="chat-bot-input">
            <input type="text" placeholder="Check available places" id="chat-bot-message-input">
            <span class="chat-bot-send-btn" id="chat-bot-message-submit"><i class="fas fa-paper-plane"></i></span>
        </div>
    </div>

</div>

airbnb_app/templates/components/footer.html
<footer id="main-footer">
    <div class="container py-5">
        <div class="row py-4">
            <div class="col-lg-4 col-md-6 mb-4 mb-lg-0 mr-lg-4">
                <h6 class="text-uppercase font-weight-bold mb-4">Newsletter</h6>
                <p class="text-muted mb-4">
                    Receive promotions, surveys, info about new realty.
                </p>
                <form action="{% url 'subscribers:new_subscription' %}" method="post">
                    {% csrf_token %}
                    <div class="p-1 rounded border">
                        <div class="input-group">
                            <input type="email" placeholder="Enter your email address"
                                   aria-describedby="button-addon1"
                                   class="form-control border-0 shadow-0"
                                   id="id_email" name="email" maxlength="254">
                            <div class="input-group-append">
                                <button id="button-addon1" type="submit" class="btn btn-link"><i class="fa fa-paper-plane"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                <h6 class="text-uppercase font-weight-bold mb-4">About</h6>
                <ul class="list-unstyled mb-0">
                    <li class="mb-2"><a href="#" class="text-muted">How Air works</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Newsroom</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Investors</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Air Plus</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Air Luxe</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Air for Work</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                <h6 class="text-uppercase font-weight-bold mb-4">Community</h6>
                <ul class="list-unstyled mb-0">
                    <li class="mb-2"><a href="#" class="text-muted">Diversity & Belonging</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Against Discrimination</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Air Associates</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Gift cards</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                <h6 class="text-uppercase font-weight-bold mb-4">Host</h6>
                <ul class="list-unstyled mb-0">
                    <li class="mb-2"><a href="#" class="text-muted">Host your home</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Resource Center</a></li>
                    <li class="mb-2"><a href="#" class="text-muted">Community Center</a></li>
                </ul>
            </div>
        </div>
    </div>
    <hr>
    <div id="sub-footer" class="py-4">
        <div class="container text-center">
            <p class="text-muted mb-0 py-2">© 2021 Air Project, Inc.</p>
            <p class="text-muted mb-0 py-2">
                This is a <a href="https://github.com/ReznikovRoman/airbnb-clone">Github project</a>.
            </p>
        </div>
    </div>
</footer>

airbnb_app/templates/components/messages.html
{% if messages %}
    <div>
        {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

airbnb_app/templates/components/navbar.html
{% load static %}
{% load main_extras %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand mr-5 brand-logo" href="{% url 'home_page' %}">
        <i class="fab fa-airbnb"></i>
        air
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0 search-form" action="{% url 'realty:search' %}">
            <input class="form-control mr-sm-2 search-field text-center"
                   type="search" placeholder="Start your search"
                   name="q"
                   aria-label="Search">
        </form>
        <div class="nav-links--right">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    {% if request.user|has_group:'hosts' %}
                        {# TODO: Host dashboard #}
                        <a class="nav-link link-host-signup" href="#">Switch to hosting</a>
                    {% else %}
                        <a class="nav-link link-host-signup" href="{% url 'hosts:become_a_host' %}">
                            Become a host
                        </a>
                    {% endif %}

                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if request.user.is_authenticated %}
                            {% if request.user.profile.profile_image %}
                                <img src="{{ request.user.profile.profile_image.url|image_size:'32x33' }}"
                                     width="32" height="33"
                                     alt="Profile image" class="rounded-circle">
                            {% else %}
                                <img src="{% static 'images/default/profile/default_profile_image.png' %}"
                                 width="32" height="33"
                                 alt="Default profile image" class="rounded-circle">
                            {% endif %}
                        {% else %}
                            <img src="{% static 'images/default/profile/default_profile_image.png' %}"
                                 width="32" height="33"
                                 alt="Default profile image" class="rounded-circle">
                        {% endif %}

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="#">Messages</a>
                            <a class="dropdown-item" href="#">Notifications</a>
                            <a class="dropdown-item" href="#">Trips</a>
                            <a class="dropdown-item" href="#">Saved</a>

                            <div class="dropdown-divider"></div>
                            {% if request.user|has_group:'hosts' %}
                                {# TODO: Host listings #}
                                <a class="dropdown-item" href="#">Manage listings</a>
                            {% else %}
                                <a class="dropdown-item" href="#">Host your home</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'accounts:settings_dashboard' %}">Account</a>

                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign up</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

airbnb_app/templates/components/pagination.html
{% load main_extras %}


{% block pagination %}
    {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a tabindex="-1" class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">
                            Previous
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a tabindex="-1" class="page-link" href="">Previous</a>
                    </li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active page-item">
                            <a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}