airbnb_app/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views


app_name = 'accounts'

urlpatterns = [
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
    ),
    path(
        route='logout/',
        view=auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path('activate/<uidb64>/<token>/', views.AccountActivationView.as_view(), name='activate'),
    path('activation-required/', views.ActivationRequiredView.as_view(), name='activation_required'),

    path('settings/', views.AccountSettingsDashboardView.as_view(), name='settings_dashboard'),
    path('settings/personal-info/', views.PersonalInfoEditView.as_view(), name='user_info_edit'),

    path('settings/login-and-security/', views.SecurityDashboardView.as_view(), name='security_dashboard'),
    path(
        route='settings/login-and-security/confirm-phone/',
        view=views.PhoneNumberConfirmPageView.as_view(),
        name='confirm_phone',
    ),
    path('settings/login-and-security/confirm-email/', views.SendConfirmationEmailView.as_view(), name='confirm_email'),

    path('show/<int:user_pk>/', views.ProfileShowView.as_view(), name='profile_show'),
    path('edit-image/', views.ProfileImageEditView.as_view(), name='edit_image'),
    path('edit-description/', views.ProfileDescriptionEditView.as_view(), name='edit_description'),

    # password change urls
    path(
        route='password_change/',
        view=auth_views.PasswordChangeView.as_view(
            template_name='accounts/registration/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done'),
         ),
        name='password_change',
    ),
    path(
        route='password_change/done/',
        view=auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
        name='password_change_done',
    ),

    # password reset urls
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path(
        route='password_reset/done/',
        view=auth_views.PasswordResetDoneView.as_view(template_name='accounts/registration/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        route='reset/<uidb64>/<token>/',
        view=auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
         ),
        name='password_reset_confirm',
    ),
    path(
        route='reset/done/',
        view=auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/registration/password_reset_complete.html',
         ),
        name='password_reset_complete',
    ),
]

airbnb_app/main/urls.py
from django.http import HttpResponse
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page'),
    path('healthcheck/', lambda response: HttpResponse(), name='healthcheck'),
    path('robots.txt', views.RobotsView.as_view(), name='robots'),
]

airbnb_app/realty/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from . import views
from .sitemaps import RealtySiteMap


sitemaps = {
    'realty': RealtySiteMap,
}

app_name = 'realty'

urlpatterns = [
    path('', views.RealtyListView.as_view(), name='all'),
    path('search/', views.RealtySearchResultsView.as_view(), name='search'),
    path('rooms/<int:pk>/<slug>/', views.RealtyDetailView.as_view(), name='detail'),
    path('city/<slug:city_slug>/', views.RealtyListView.as_view(), name='all_by_city'),

    # Edit realty
    path('new/', views.RealtyEditView.as_view(), name='new_realty'),
    path('<int:realty_id>/edit/', views.RealtyEditView.as_view(), name='edit_realty'),

    # Realty - steps
    path('new/info/', views.RealtyGeneralInfoEditView.as_view(), name='new_realty_info'),
    path('new/location/', views.RealtyLocationEditView.as_view(), name='new_realty_location'),
    path('new/description/', views.RealtyDescriptionEditView.as_view(), name='new_realty_description'),

    # Images
    path('image/order/', views.RealtyImageOrderView.as_view(), name='image_change_order'),

    # Sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

airbnb_app/accounts/models.py
from model_utils import FieldTracker
from phonenumber_field.modelfields import PhoneNumberField

from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager, Permission, PermissionsMixin
from django.core.validators import MinLengthValidator
from django.db import models

from common.utils import select_file_storage


class CustomUserManager(BaseUserManager):
    """Manager for CustomUser model."""

    def create_user(self, email: str, first_name: str, last_name: str, password: str = None):
        if not email:
            raise ValueError('Users must have an email address.')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email: str, first_name: str, last_name: str, password: str):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email: str, first_name: str, last_name: str, password: str):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def get_or_create(self, email: str, first_name: str = None, last_name: str = None, password: str = None):
        created = True
        try:
            user = self.get(
                email=self.normalize_email(email),
            )
            created = False
        except CustomUser.DoesNotExist:
            user = self.create_user(
                email=self.normalize_email(email),
                first_name=first_name,
                last_name=last_name,
                password=password,
            )
            user.save(using=self._db)
        return user, created


class ActivatedAccountsManager(CustomUserManager):
    """Manager for all users that have confirmed their email."""

    def get_queryset(self):
        base_qs = super(ActivatedAccountsManager, self).get_queryset()
        return base_qs.filter(is_email_confirmed=True)


class CustomUser(AbstractUser, PermissionsMixin):
    """Custom user model."""

    profile: "Profile"
    username = None
    email = models.EmailField(
        verbose_name='email',
        max_length=60,
        unique=True,
    )
    first_name = models.CharField(
        verbose_name='first name',
        max_length=40,
    )
    last_name = models.CharField(
        verbose_name='last name',
        max_length=40,
    )
    is_email_confirmed = models.BooleanField(verbose_name='email confirmed', default=False)
    date_joined = models.DateTimeField(
        verbose_name='date joined',
        auto_now_add=True,
    )
    last_login = models.DateTimeField(
        verbose_name='last login',
        auto_now=True,
    )
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomUserManager()
    activated = ActivatedAccountsManager()

    # login parameter
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    # email field tracker
    email_tracker = FieldTracker(fields=['email'])

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.email

    def get_all_permissions(self, obj=None):
        if self.is_active and self.is_superuser:
            return Permission.objects.all()
        return Permission.objects.filter(user=self)

    def has_perm(self, perm, obj=None):
        if perm in self.get_all_permissions() or perm in self.get_group_permissions():
            return True
        return False

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


def get_profile_image_upload_path(instance: "Profile", filename: str) -> str:
    return f"upload/users/{instance.user.email}/profile/{filename}"


def get_default_profile_image() -> str:
    return "default/profile/default_profile_image.png"


def get_default_profile_image_full_url() -> str:
    return f"{settings.MEDIA_URL}{get_default_profile_image()}"


class ProfileGenderChoices(models.TextChoices):
    MALE = 'M', 'Male'
    FEMALE = 'F', 'Female'
    OTHER = 'O', 'Other'


class Profile(models.Model):
    """Profile for CustomUser."""

    profile_image = models.ImageField(
        verbose_name='profile image',
        blank=True,
        null=True,
        storage=select_file_storage,
        upload_to=get_profile_image_upload_path,
        default=get_default_profile_image,
    )
    date_of_birth = models.DateField(
        verbose_name='date of birth',
        blank=True,
        null=True,
    )
    gender = models.CharField(
        verbose_name='gender',
        blank=True,
        max_length=2,
        choices=ProfileGenderChoices.choices,
    )
    phone_number = PhoneNumberField(
        verbose_name='phone number',
        blank=True,
        null=True,
        unique=True,
    )
    is_phone_number_confirmed = models.BooleanField(
        verbose_name='is phone number confirmed',
        default=False,
    )
    description = models.TextField(
        verbose_name='description',
        blank=True,
    )
    user: CustomUser = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='profile',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return f"Profile for {self.user}"


class SMSLog(models.Model):
    """Log of sms message that is sent to User to verify his phone number."""

    sms_code = models.CharField(
        verbose_name='4 digits sms code',
        blank=True,
        max_length=4,
        validators=[
            MinLengthValidator(4),
        ],
    )
    profile = models.OneToOneField(
        Profile,
        related_name='sms_log',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'sms log'
        verbose_name_plural = 'sms logs'

    def __str__(self):
        return f"Code `{self.sms_code}` for {self.profile.user}"

airbnb_app/accounts/forms.py
from typing import Union

from django import forms
from django.contrib.auth.forms import PasswordResetForm, UserChangeForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import CustomUser, Profile
from .tasks import send_password_reset_code


class SignUpForm(UserCreationForm):
    """Form for signing up/creating new account."""

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = 'Email address'


class CustomPasswordResetForm(PasswordResetForm):
    """Custom password reset form.

    Send emails using Celery.
    """

    def send_mail(
            self,
            subject_template_name,
            email_template_name,
            context,
            from_email,
            to_email,
            html_email_template_name=None,
    ):
        context['user'] = context['user'].pk
        send_password_reset_code.delay(
            subject_template_name=subject_template_name,
            email_template_name=email_template_name,
            context=context,
            from_email=from_email,
            to_email=to_email,
            html_email_template_name=html_email_template_name,
        )


class AdminCustomUserChangeForm(UserChangeForm):
    """Form for editing CustomUser (used on the admin panel)."""

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'is_email_confirmed')


class UserInfoForm(forms.ModelForm):
    """Form for editing user info."""

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    """Form for editing user profile."""

    class Meta:
        model = Profile
        fields = ('gender', 'date_of_birth', 'phone_number')
        widgets = {
            'date_of_birth': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date',
                },
            ),
        }

    def clean_date_of_birth(self):
        """Handles input of date_of_birth field.

        date of birth can't be in the future, Host must be at least 18 years old
        """
        date_of_birth = self.cleaned_data['date_of_birth']
        if date_of_birth:
            date_now = timezone.now().date()
            year_diff = (date_now.month, date_now.day) < (date_of_birth.month, date_of_birth.day)
            host_age = date_now.year - date_of_birth.year - year_diff
            if date_of_birth > date_now:
                raise ValidationError('Invalid date: date of birth in the future.', code='invalid')
            elif host_age < 18:
                raise ValidationError('Invalid date: You must be at least 18 years old.', code='underage')
        return date_of_birth


class ProfileImageForm(forms.ModelForm):
    """Form for uploading profile image."""

    class Meta:
        model = Profile
        fields = ('profile_image',)
        widgets = {
            'profile_image': forms.FileInput(),
        }


class ProfileDescriptionForm(forms.ModelForm):
    """Form for editing user description ('about me' section)."""

    class Meta:
        model = Profile
        fields = ('description',)


class VerificationCodeForm(forms.Form):
    """Form for entering a SMS verification code."""

    digit_1 = forms.CharField(
        min_length=1,
        max_length=1,
        widget=forms.NumberInput(
            attrs={'min': '0', 'max': '9', 'class': 'code', 'placeholder': '0'},
        ),
        label='',
    )
    digit_2 = forms.CharField(
        min_length=1,
        max_length=1,
        widget=forms.NumberInput(
            attrs={'min': '0', 'max': '9', 'class': 'code', 'placeholder': '0'},
        ),
        label='',
    )
    digit_3 = forms.CharField(
        min_length=1,
        max_length=1,
        widget=forms.NumberInput(
            attrs={'min': '0', 'max': '9', 'class': 'code', 'placeholder': '0'},
        ),
        label='',
    )
    digit_4 = forms.CharField(
        min_length=1,
        max_length=1,
        widget=forms.NumberInput(
            attrs={'min': '0', 'max': '9', 'class': 'code', 'placeholder': '0'},
        ),
        label='',
    )

    def clean_digit_1(self):
        return self._clean_digit(digit_index=1)

    def clean_digit_2(self):
        return self._clean_digit(digit_index=2)

    def clean_digit_3(self):
        return self._clean_digit(digit_index=3)

    def clean_digit_4(self):
        return self._clean_digit(digit_index=4)

    def _clean_digit(self, digit_index: Union[str, int], digit_template: str = 'digit_'):
        digit = f"{digit_template}{str(digit_index)}"
        data = self.cleaned_data.get(digit)

        if not 0 <= int(data) <= 9:
            raise ValidationError('Digit must be in range [0, 9].')

        return data

airbnb_app/accounts/api/views.py
from rest_framework_simplejwt.views import TokenObtainPairView

from .serializers import CustomTokenObtainPairSerializer


class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer

airbnb_app/accounts/templates/accounts/profile/edit_description.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Profile image &bull; Air
{% endblock %}

{% block content %}
    <div class="edit-description">
        <div class="edit-description--header">
            <div class="profile--links">
                <span class="profile--link">
                    <a href="{% url 'accounts:profile_show' user_pk=request.user.pk %}">Profile</a>
                </span>
                <span class="description--link active">
                    Profile description
                </span>
            </div>
            <h1>Profile description</h1>
        </div>

        <div class="profile-description--form">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% bootstrap_form profile_description_form %}

                <div class="form-buttons">
                    <input type="submit" class="button button-secondary" value="Save">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

airbnb_app/accounts/templates/accounts/profile/edit_image.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load main_extras %}


{% block title %}
    Profile image &bull; Air
{% endblock %}

{% block content %}
    <div class="edit-image">
        <div class="edit-image--header">
            <div class="profile--links">
                <span class="profile--link">
                    <a href="{% url 'accounts:profile_show' user_pk=request.user.pk %}">Profile</a>
                </span>
                <span class="image--link active">
                    Profile image
                </span>
            </div>
            <h1>Profile image</h1>
        </div>
        <div class="profile-image--form">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="image-group">
                    <div class="image-preview">
                        <div id="profile-image"
                             style='background: url("{% if request.user.profile.profile_image %}{{ request.user.profile.profile_image.url|image_size:'145x145' }}{% else %}{% static 'images/default/profile/default_profile_image.png' %}{% endif %}") no-repeat; background-size: 100% 100%'>
                        </div>
                    </div>
                    {% bootstrap_form profile_image_form %}
                </div>

                <div class="form-buttons">
                    <input type="submit" class="button button-secondary" value="Save">
                </div>
            </form>
        </div>
    </div>
{% endblock %}


{% block domready %}
    const profileImage = $('#profile-image');
    const profileImageInput = $('#id_profile_image');

    function readURL(input) {
        if (input.files && input.files[0]) {
            const reader = new FileReader();
            reader.onload = function(e) {
                $(profileImage).css('background-image', 'url('+e.target.result +')');
                $(profileImage).css('background-size', '100% 100%');
                $(profileImage).hide();
                $(profileImage).fadeIn(650);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    profileImageInput.change(function() {
        readURL(this);
    });
{% endblock %}

airbnb_app/accounts/templates/accounts/profile/show.html
{% extends 'base.html' %}
{% load static %}
{% load main_extras %}


{% block title %}
    {{ profile_owner.full_name }}'s Profile &bull; Air
{% endblock %}

{% block content %}
    <div class="profile-show">
        <div class="profile-card">
            <div class="profile-photo">
                <img src="{{ profile_owner.profile.profile_image.url|image_size:'128x128' }}"
                     width="128" height="128"
                     alt="Profile image" class="rounded-circle">
                {% if is_profile_of_current_user %}
                    <a href="{% url 'accounts:edit_image' %}" class="color-secondary">Update photo</a>
                {% endif %}
            </div>
            
            {% if profile_owner.is_email_confirmed or profile_owner.profile.is_phone_number_confirmed %}
                <hr>
                <div class="confirmed-details">
                    <h3>{{ profile_owner.first_name }} confirmed</h3>
                    <ul>
                        {% if profile_owner.is_email_confirmed %}
                            <li class="confirmed-detail">
                                <span class="check-icon"><i class="fas fa-check"></i></span>
                                <span>Email address</span>
                            </li>
                        {% endif %}
                        {% if profile_owner.profile.is_phone_number_confirmed %}
                            <li class="confirmed-detail">
                                <span class="check-icon"><i class="fas fa-check"></i></span>
                                <span>Phone number</span>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="profile-info">
            <div class="profile-header">
                <h1>Hi, I'm {{ profile_owner.first_name }}</h1>
                <p class="color-secondary joined-date">Joined in {{ profile_owner.date_joined|date:"Y" }}</p>
                {% if is_profile_of_current_user %}
                    <a href="{% url 'accounts:edit_description' %}">Edit profile</a>
                {% endif %}
            </div>
            {% with profile_description=profile_owner.profile.description  %}
                {% if profile_description %}
                    <div class="about-section">
                        <h2>About</h2>
                        <div class="description">
                            <p>{{ profile_description }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endwith %}

            {% if host_listings.exists %}
                <hr>
                <div class="listings-section">
                    <h2>{{ profile_owner.first_name }}'s listings</h2>
                    <div class="listings">
                        <div class="splide">
                            <div class="splide__track">
                                <ul class="splide__list listings-carousel">
                                    {% for host_listing in host_listings %}
                                        <li class="carousel-content splide__slide">
                                            <div class="listing">
                                                <a href="{% url 'realty:detail' pk=host_listing.pk slug=host_listing.slug %}">
                                                    {% if host_listing.images.exists %}
                                                        <img src="{{ host_listing.images.first.image.url|image_size:'306x204' }}"
                                                             width="306" height="204" alt="Realty image">
                                                    {% else %}
                                                        <img src="{% static 'realty/images/default/realty_image_placeholder.png' %}"
                                                             width="300" height="200" alt="Realty image">
                                                    {% endif %}
                                                </a>
                                                <div class="listing-details">
                                                    <p class="listing-type">{{ host_listing.realty_type }}</p>
                                                    <a href="{% url 'realty:detail' pk=host_listing.pk slug=host_listing.slug %}"
                                                       class="listing-link">
                                                        <p class="listing-name">{{ host_listing.name }}</p>
                                                    </a>
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}


{% block domready %}
    new Splide( '.splide', {
        perPage: 1,
        gap: '1rem',
        rewind: false,
        autoWidth: true,
        lazyLoad: 'nearby',
        breakpoints: {
            height: '8rem',
        },
    } ).mount();
{% endblock %}