airbnb_app/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views


app_name = 'accounts'

urlpatterns = [
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
    ),
    path(
        route='logout/',
        view=auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path('activate/<uidb64>/<token>/', views.AccountActivationView.as_view(), name='activate'),
    path('activation-required/', views.ActivationRequiredView.as_view(), name='activation_required'),

    path('settings/', views.AccountSettingsDashboardView.as_view(), name='settings_dashboard'),
    path('settings/personal-info/', views.PersonalInfoEditView.as_view(), name='user_info_edit'),

    path('settings/login-and-security/', views.SecurityDashboardView.as_view(), name='security_dashboard'),
    path(
        route='settings/login-and-security/confirm-phone/',
        view=views.PhoneNumberConfirmPageView.as_view(),
        name='confirm_phone',
    ),
    path('settings/login-and-security/confirm-email/', views.SendConfirmationEmailView.as_view(), name='confirm_email'),

    path('show/<int:user_pk>/', views.ProfileShowView.as_view(), name='profile_show'),
    path('edit-image/', views.ProfileImageEditView.as_view(), name='edit_image'),
    path('edit-description/', views.ProfileDescriptionEditView.as_view(), name='edit_description'),

    # password change urls
    path(
        route='password_change/',
        view=auth_views.PasswordChangeView.as_view(
            template_name='accounts/registration/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done'),
         ),
        name='password_change',
    ),
    path(
        route='password_change/done/',
        view=auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
        name='password_change_done',
    ),

    # password reset urls
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path(
        route='password_reset/done/',
        view=auth_views.PasswordResetDoneView.as_view(template_name='accounts/registration/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        route='reset/<uidb64>/<token>/',
        view=auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
         ),
        name='password_reset_confirm',
    ),
    path(
        route='reset/done/',
        view=auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/registration/password_reset_complete.html',
         ),
        name='password_reset_complete',
    ),
]

airbnb_app/main/urls.py
from django.http import HttpResponse
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page'),
    path('healthcheck/', lambda response: HttpResponse(), name='healthcheck'),
    path('robots.txt', views.RobotsView.as_view(), name='robots'),
]

airbnb_app/realty/api/urls.py
from django.urls import path

from . import views


app_name = 'realty'

urlpatterns = [
    path('realty/', views.RealtyListApiView.as_view(), name='realty_list'),
    path('realty/<int:pk>/', views.RealtyDetailApiView.as_view(), name='realty_detail'),
]

airbnb_app/realty/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from . import views
from .sitemaps import RealtySiteMap


sitemaps = {
    'realty': RealtySiteMap,
}

app_name = 'realty'

urlpatterns = [
    path('', views.RealtyListView.as_view(), name='all'),
    path('search/', views.RealtySearchResultsView.as_view(), name='search'),
    path('rooms/<int:pk>/<slug>/', views.RealtyDetailView.as_view(), name='detail'),
    path('city/<slug:city_slug>/', views.RealtyListView.as_view(), name='all_by_city'),

    # Edit realty
    path('new/', views.RealtyEditView.as_view(), name='new_realty'),
    path('<int:realty_id>/edit/', views.RealtyEditView.as_view(), name='edit_realty'),

    # Realty - steps
    path('new/info/', views.RealtyGeneralInfoEditView.as_view(), name='new_realty_info'),
    path('new/location/', views.RealtyLocationEditView.as_view(), name='new_realty_location'),
    path('new/description/', views.RealtyDescriptionEditView.as_view(), name='new_realty_description'),

    # Images
    path('image/order/', views.RealtyImageOrderView.as_view(), name='image_change_order'),

    # Sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

airbnb_app/realty/api/views.py
from rest_framework import generics, status
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.request import Request
from rest_framework.response import Response

from ..filters import RealtyFilter
from ..services.realty import get_all_available_realty
from .permissions import IsAbleToAddRealty, IsRealtyOwnerOrReadOnly
from .serializers import RealtySerializer, RealtyUpdateSerializer


# TODO: refactor API


class RealtyListApiView(generics.ListCreateAPIView):
    """API view for listing realty objects.

    get:
    Return a list of all available Realty objects.

    post:
    Create a new Realty object.
    """

    queryset = get_all_available_realty()
    serializer_class = RealtySerializer
    filterset_class = RealtyFilter
    permission_classes = (
        IsAbleToAddRealty,
    )

    def post(self, request: Request, *args, **kwargs):
        # TODO: finish API (`hosts`)
        host_pk = request.user.host.id
        request.data['host_pk'] = host_pk
        request.data['host'] = {'user': {'profile': {}}}

        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save(host_pk=host_pk)
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RealtyDetailApiView(generics.RetrieveUpdateDestroyAPIView):
    """API view for a single Realty object.

    retrieve:
    Return a Realty object by the given id.

    put:
    Update some of the Realty object's fields.

    delete:
    Delete a Realty object by the given id.
    """

    queryset = get_all_available_realty()
    serializer_class = RealtyUpdateSerializer
    permission_classes = (
        IsAuthenticatedOrReadOnly,
        IsRealtyOwnerOrReadOnly,
    )

airbnb_app/realty/views.py
from typing import List, Optional

from braces.views import JsonRequestResponseMixin

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, reverse
from django.views import generic

from addresses.forms import AddressForm
from addresses.models import Address
from common.collections import FormWithModel
from common.services import get_field_names_from_form, get_keys_with_prefixes, get_required_fields_from_form_with_model
from common.session_handler import SessionHandler
from hosts.models import RealtyHost

from .constants import MAX_REALTY_IMAGES_COUNT, REALTY_FORM_KEYS_COLLECTOR_NAME, REALTY_FORM_SESSION_PREFIX
from .filters import RealtyShortFilter
from .forms import (
    RealtyDescriptionForm, RealtyFiltersForm, RealtyForm, RealtyGeneralInfoForm, RealtyImageFormSet, RealtyTypeForm,
)
from .mixins import RealtySessionDataRequiredMixin
from .models import CustomDeleteQueryset, Realty, RealtyImage
from .services.images import get_images_by_realty_id, update_images_order
from .services.order import convert_response_to_orders
from .services.realty import (
    get_all_available_realty, get_amenity_ids_from_session, get_available_realty_by_city_slug,
    get_available_realty_filtered_by_type, get_available_realty_search_results,
    get_cached_realty_visits_count_by_realty_id, get_or_create_realty_host_by_user, update_realty_visits_count,
)


class RealtySearchResultsView(generic.ListView):
    model = Realty
    template_name = 'realty/realty/search_results.html'
    realty_type_form: RealtyTypeForm = None
    realty_filters_form: RealtyFiltersForm = None

    def dispatch(self, request, *args, **kwargs):
        self.realty_type_form = RealtyTypeForm()
        self.realty_filters_form = RealtyFiltersForm()
        return super(RealtySearchResultsView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        realty_search_results = get_available_realty_search_results(self.request.GET.get('q', None))

        realty_types: List[str] = self.request.GET.getlist('realty_type', None)
        if realty_types:
            realty_search_results = get_available_realty_filtered_by_type(
                realty_types=realty_types,
                realty_qs=realty_search_results,
            )

        realty_search_results = RealtyShortFilter(self.request.GET, realty_search_results).qs

        return realty_search_results

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RealtySearchResultsView, self).get_context_data(**kwargs)
        search_query: str = self.request.GET.get('q')

        context['search_query'] = search_query
        context['realty_count'] = self.get_queryset().count()
        context['realty_type_form'] = self.realty_type_form
        context['realty_filters_form'] = self.realty_filters_form
        context['meta_description'] = f"Search results for `{search_query}`"

        return context


class RealtyListView(generic.ListView):
    """Display all available realty objects."""

    model = Realty
    template_name = 'realty/realty/list.html'
    paginate_by = 3
    realty_type_form: RealtyTypeForm = None
    realty_filters_form: RealtyFiltersForm = None

    def dispatch(self, request, *args, **kwargs):
        self.realty_type_form = RealtyTypeForm()
        self.realty_filters_form = RealtyFiltersForm()
        return super(RealtyListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        available_realty = get_all_available_realty()

        city_slug: str = self.kwargs.get('city_slug', None)
        if city_slug:
            available_realty = get_available_realty_by_city_slug(city_slug=city_slug)

        realty_types: List[str] = self.request.GET.getlist('realty_type', None)
        if realty_types:
            available_realty = get_available_realty_filtered_by_type(
                realty_types=realty_types,
                realty_qs=available_realty,
            )

        available_realty = RealtyShortFilter(data=self.request.GET, queryset=available_realty).qs

        return available_realty

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RealtyListView, self).get_context_data(**kwargs)
        city_slug = self.kwargs.get('city_slug', 'All cities')
        city: str = city_slug.capitalize()

        context['realty_count'] = self.get_queryset().count()
        context['city'] = city
        context['meta_description'] = f"List of places in {city}"
        context['realty_type_form'] = self.realty_type_form
        context['realty_filters_form'] = self.realty_filters_form

        return context


class RealtyDetailView(generic.DetailView):
    """Display a single available Realty."""

    model = Realty
    template_name = 'realty/realty/detail.html'
    queryset = get_all_available_realty()

    def get(self, request: HttpRequest, *args, **kwargs):
        update_realty_visits_count(self.get_object().id)
        return super(RealtyDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(RealtyDetailView, self).get_context_data(**kwargs)
        realty_object: Realty = self.get_object()

        context['realty_views_count'] = (
                realty_object.visits_count +
                get_cached_realty_visits_count_by_realty_id(realty_id=realty_object.id)
        )

        return context


class RealtyEditView(
    LoginRequiredMixin,
    RealtySessionDataRequiredMixin,
    generic.base.TemplateResponseMixin,
    generic.View,
):
    """View for creating or updating a single Realty."""

    template_name = 'realty/realty/form.html'

    realty: Realty = None
    address: Address = None
    realty_images: 'CustomDeleteQueryset[RealtyImage]' = None

    is_creating_new_realty: bool = True  # True if we are creating new Realty, False otherwise
    realty_form: RealtyForm = None
    address_form: AddressForm = None
    realty_address_initial: dict = None
    realty_info_initial: dict = None

    session_handler: SessionHandler = None

    def dispatch(self, request: HttpRequest, realty_id: Optional[int] = None, *args, **kwargs):
        self.session_handler = SessionHandler(
            session=request.session,
            keys_collector_name=REALTY_FORM_KEYS_COLLECTOR_NAME,
            session_prefix=REALTY_FORM_SESSION_PREFIX,
        )

        if realty_id is not None:  # if we are editing an existing Realty object
            self.realty = get_object_or_404(Realty, id=realty_id)

            # if a current user is not the host of the Realty
            if (not hasattr(request.user, 'host')) or (self.realty.host != request.user.host):
                return redirect(reverse('realty:all'))

            self.address = self.realty.location
            self.is_creating_new_realty = False
            self.realty_images = self.realty.images.all()
            self.required_session_data = []
        else:
            self.required_session_data = get_keys_with_prefixes(
                names=get_required_fields_from_form_with_model(
                    forms_with_models=[
                        FormWithModel(RealtyGeneralInfoForm, Realty),
                        FormWithModel(AddressForm, Address),
                        FormWithModel(RealtyDescriptionForm, Realty),
                    ],
                ),
                prefix=REALTY_FORM_SESSION_PREFIX,
            )

            self.realty_info_initial = self.session_handler.get_items_by_keys(
                keys=get_field_names_from_form(RealtyForm),
            )
            # handle m2m field
            self.realty_info_initial['amenities'] = get_amenity_ids_from_session(self.session_handler)

            self.realty_address_initial = self.session_handler.get_items_by_keys(
                keys=get_field_names_from_form(AddressForm),
            )

        self.realty_form = RealtyForm(
            data=request.POST or None,
            instance=self.realty,
            initial=self.realty_info_initial,
        )
        self.address_form = AddressForm(
            data=request.POST or None,
            instance=self.address,
            initial=self.realty_address_initial,
        )
        return super(RealtyEditView, self).dispatch(request, realty_id, *args, **kwargs)

    def get(self, request: HttpRequest, realty_id: Optional[int] = None, *args, **kwargs):
        realty_image_formset = RealtyImageFormSet(queryset=get_images_by_realty_id(realty_id))

        return self.render_to_response(
            context={
                'realty_form': self.realty_form,
                'address_form': self.address_form,
                'realty_image_formset': realty_image_formset,
                'is_creating_new_realty': self.is_creating_new_realty,
                'realty_images': self.realty_images,
                'max_realty_images_count': MAX_REALTY_IMAGES_COUNT,
            },
        )

    def post(self, request: HttpRequest, realty_id: Optional[int] = None, *args, **kwargs):
        realty_image_formset = RealtyImageFormSet(
            data=request.POST,
            files=request.FILES,
            queryset=get_images_by_realty_id(realty_id),
        )

        if self.realty_form.is_valid():
            new_realty: Realty = self.realty_form.save(commit=False)
            realty_host: RealtyHost = get_or_create_realty_host_by_user(user=request.user)[0]
            new_realty.host = realty_host

            if self.address_form.is_valid():
                new_address: Address = self.address_form.save()
                new_realty.location = new_address

                if realty_id is None:  # if it is a new Realty
                    self.session_handler.flush_keys_collector()

                new_realty.save()
                self.realty_form.save_m2m()

                if realty_image_formset.is_valid():

airbnb_app/realty/templates/realty/realty/form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load main_extras %}


{% block title %}
    {% if is_creating_new_realty %}
        New realty
    {% else %}
        Edit realty
    {% endif %}
     &bull; Air
{% endblock %}

{% block content %}
    {% if is_creating_new_realty %}
        <h1>Create new realty</h1>
    {% else %}
        <h1>Edit your realty</h1>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form realty_form %}
        {% bootstrap_form address_form %}

        <div class="image-form-group">
            {{ realty_image_formset.management_form }}

            {% for image_form in realty_image_formset %}
                {{ image_form.id }}
                <div class="image-upload">
                    {{ image_form.as_p }}
                    <div class="image-preview">
                        {% if is_creating_new_realty %}
                            <div id="image-{{ forloop.counter0 }}"
                                 style='background: url("{% static 'realty/images/default/realty_image_placeholder.png' %}")'>
                            </div>
                        {% else %}
                            {% for realty_image in realty_images %}
                                {% if forloop.counter0 == forloop.parentloop.counter0 %}
                                    <div id="image-{{ forloop.parentloop.counter0 }}"
                                         data-id="{{ realty_image.id }}"
                                         style='background: url("{{ realty_image.image.url|image_size:'145x145' }}") no-repeat; background-size: 100% 100%'>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="form-buttons">
            {% if is_creating_new_realty %}
                <a href="{% url 'realty:new_realty_description' %}" class="button button-dark">Previous</a>
            {% endif %}
            <input type="submit" value="Save" class="button">
        </div>
    </form>
{% endblock %}


{% block domready %}


    // Change label text
    $('.image-upload p label').each(function () {
        $(this).html($('<i class="fas fa-cloud-upload-alt"></i>'));
    });

    const imagePreviewsDom = $('.image-preview');
    let imagesDom = $('div[id^=image-]');
    const imageInputsDom = $('input[name*=-image]');

    imagePreviewsDom.each(function (index) {
        if (imagesDom.size !== {{ max_realty_images_count }}) {
            if ($(this).find($('div[id^=image-]')).length !== 1) {
                $(this).append(`<div id="image-${index}" style='background: url("{% static 'realty/images/default/realty_image_placeholder.png' %}")'></div>`);
            }
        }
    });

    imagesDom = $('div[id^=image-]');

    function readURL(input, index) {
        if (input.files && input.files[0]) {
            const reader = new FileReader();
            reader.onload = function(e) {
                $(imagesDom[index]).css('background-image', 'url('+e.target.result +')');
                $(imagesDom[index]).css('background-size', '100% 100%');
                $(imagesDom[index]).hide();
                $(imagesDom[index]).fadeIn(650);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    imageInputsDom.each(function (index) {
        $(this).change(function() {
            readURL(this, index);
        });
    });


    // js - sortable
    {% if not is_creating_new_realty %}
        $('.image-form-group').sortable({
            stop: function (event, ui) {
                const imagesOrder = {};
                $('.image-form-group div[id^=image-]').each(function () {

                    const images = $('.image-upload');
                    const currentImage = $(this).closest('.image-preview').closest('.image-upload');

                    // associate the image's id with its order
                    imagesOrder[$(this).data('id')] = images.index(currentImage);
                });
                $.ajax({
                    type: 'POST',
                    url: "{% url 'realty:image_change_order' %}",
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json',
                    data: JSON.stringify(imagesOrder)
                });
            }
        });
    {% endif %}

{% endblock %}

airbnb_app/realty/templates/realty/realty/list.html
{% extends 'base.html' %}
{% load static %}
{% load main_extras %}


{% block title %}
    {{ city }} &bull; Stays &bull; Air
{% endblock %}

{% block meta_tags %}
    <meta property="og:title" content="{{ city }} | Stays | Air">
    <meta name="description" property="og:description" content="{{ meta_description }}">
    <meta property="og:url" content="{{ ABSOLUTE_URL }}">
    <meta name="twitter:card" value="summary">
{% endblock %}

{% block content %}
    <div class="realty-list">
        <div class="header mb-3">
            <p class="color-secondary">{{ realty_count }}+ stay{{ realty_count|pluralize }}</p>
            <h1>Stays in {{ city }}</h1>
        </div>

        <div class="filter-row">
            <div class="filter--dropdown" id="filters-type--dropdown">
                <button class="button-filter" id="realty-type--btn">
                    <span>Type of place</span>
                </button>
                <form action="{% url 'realty:all_by_city' city_slug=city|slugify %}"
                      class="realty-filter--form hidden" method="get">
                    {{ realty_type_form.as_p }}

                    <hr class="form-footer--divider">
                    <div class="form-footer">
                        <input type="submit" value="Save">
                    </div>
                </form>
            </div>
            <div class="filter--dropdown" id="filters-all--dropdown">
                <button class="button-filter" id="realty-filters-all--btn">
                    <span>More filters</span>
                </button>
            </div>
        </div>

        <div class="filter-popup hidden">
            <button class="close-popup">&times;</button>
            <div class="popup-header">
                <h3>More filters</h3>
            </div>
            <form action="{% url 'realty:all_by_city' city_slug=city|slugify %}"
                      class="property-filter-all--form" method="get">
                {% if realty_filters_form %}
                    <!-- Form Errors -->
                    {% if realty_filters_form.errors %}
                        <ul class="errors">
                            {% for error in realty_filters_form.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {% regroup realty_filters_form by field.group as field_groups %}
                    {% for field_group in field_groups %}
                        {% if field_group.grouper == 1 %}
                            <div class="form-section" id="section--guests">
                                <div class="form-section--header">
                                    <h2>Guests and beds</h2>
                                </div>
                                {% for field in field_group.list %}
                                    <div class="form-input">
                                        <label>{{ field.label }}</label>
                                        <div class="input-number--select">
                                            <button class="input-number--subtract" type="button">-</button>
                                            {{ field }}
                                            <button class="input-number--add" type="button">+</button>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="form-section" id="section--amenities">
                                <div class="form-section--header">
                                    <h2>Amenities</h2>
                                </div>
                                {% for field in field_group.list %}
                                    <div class="form-input">
                                        <div class="form-input">
                                            {{ field }}
                                            <label>{{ field.label }}</label>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}

                <hr class="form-footer--divider">
                <div class="form-footer">
                    <input type="submit" value="Show places">
                </div>
            </form>
        </div>
        <div class="realty">
            {% for realty in realty_list %}
                <div class="realty-card">
                    <div class="realty-card--image">
                        <a href="{% url 'realty:detail' pk=realty.id slug=realty.slug %}">
                            {% if realty.images.exists %}
                                <img src="{{ realty.images.first.image.url|image_size:'300x200' }}"
                                     width="300" height="200" alt="Realty image">
                            {% else %}
                                <img src="{% static 'realty/images/default/realty_image_placeholder.png' %}"
                                     width="300" height="200" alt="Realty image">
                            {% endif %}
                        </a>
                    </div>
                    <div class="realty-card--description">
                        <div class="realty-card--name">
                            <a href="{% url 'realty:detail' pk=realty.id slug=realty.slug %}">
                                <p class="realty-card--short-description color-secondary mb-0">
                                    {{ realty.realty_type }} in {{ realty.location.street }}
                                </p>
                            </a>
                            <a href="{% url 'realty:detail' pk=realty.id slug=realty.slug %}"><h4>{{ realty.name }}</h4></a>
                        </div>
                        <hr class="divider--short">
                        <div class="realty-card--properties">
                            <ul class="rooms color-secondary">
                                {% with realty_views=realty.visits_count  %}
                                    <li>{{ realty_views }} view{{ realty_views|pluralize }}</li>
                                {% endwith %}
                            </ul>
                            <ul class="rooms color-secondary">
                                {% with max_guests_count=realty.max_guests_count  %}
                                    <li>{{ max_guests_count }} guest{{ max_guests_count|pluralize }}</li>
                                {% endwith %}
                                {% with beds_count=realty.beds_count  %}
                                    <li>{{ beds_count }} bed{{ beds_count|pluralize }}</li>
                                {% endwith %}
                            </ul>
                            <ul class="amenities color-secondary">
                                {% for amenity in realty.amenities.all %}
                                    <li>{{ amenity.name }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="realty-card--footer">
                            <div class="realty-price">
                                <span class="price">{{ realty.price_per_night }}$</span> / night
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}


{% block domready %}

    // Realty filter form - checkboxes
    const filterCheckboxes = $('.realty-filter--form').find('input[type="checkbox"]');

    const search = window.location.search.slice(1).split('&');
    const realtyTypes = [];
    search.forEach(realtyType => realtyTypes.push(realtyType.split('=')[1]));

    filterCheckboxes.each(function () {
        if (realtyTypes.indexOf($(this).val()) >= 0) $(this).prop('checked', true);
    });


    $('.realty-card').before('<hr>');
    $('.form-section').before('<hr>');

    const realtyTypeBtn = $('#realty-type--btn');
    const realtyTypeForm = realtyTypeBtn.siblings('form');


    realtyTypeBtn.click(
        function (e) {
            realtyTypeForm.toggleClass('hidden');
            e.stopPropagation();
        }
    );
    realtyTypeForm.click(function (e) {
        e.stopPropagation();
    });

    $('body').click(function () {
        if (!realtyTypeForm.hasClass('hidden')) realtyTypeForm.toggleClass('hidden');
    });

    document.addEventListener(
        'keydown',
        function (event) {
            if (event.key === 'Escape') {
                if (!realtyTypeForm.hasClass('hidden')) realtyTypeForm.toggleClass('hidden');
            }
        }
    );

{% endblock %}